In [1]:
import cv2 as marcel

In [2]:
import numpy as np

# Import libary

In [3]:
pict = marcel.imread('prak.jpg')

In [4]:
marcel.imshow('pict asli', pict)
marcel.waitKey(0)
marcel.destroyAllWindows()

In [5]:
print(pict.shape)
print(pict.dtype) #untuk mengetahui type data apa yang digunakan dlm variabel

(128, 128, 3)
uint8


In [6]:
b = pict[:,:,0]
g = pict[:,:,1]
r = pict[:,:,2]

# convert RGB IMAGE

In [13]:
panjang = len(pict)
lebar = len(pict[0]) # Perbaikan: mengambil panjang lebar dari pict[0], bukan len(pict)

marcel_gray = np.zeros((panjang, lebar), dtype=np.uint8) # Perbaikan: menambahkan tipe data uint8 pada inisialisasi array

for i in range(panjang):
    for j in range(lebar):
        marcel_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j] # Perbaikan: menghapus koma di depan nilai 2989 dan 1141
marcel_gray = marcel_gray.astype(np.uint8)


In [14]:
marcel.imshow('pict asli', marcel_gray)
marcel.waitKey(0)
marcel.destroyAllWindows()

In [12]:
print(marcel_gray)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]


In [15]:
panjang = len(pict)
lebar = len(pict[0]) # Perbaikan: mengambil panjang lebar dari pict[0], bukan len(pict)

ambang = 255 #Variabel ambang diinisialisasi dengan nilai 255, yang digunakan sebagai ambang batas untuk konversi menjadi citra biner. Piksel dengan nilai intensitas yang lebih besar atau sama dengan ambang akan dikonversi menjadi 0 (hitam), dan piksel dengan nilai intensitas yang lebih kecil dari ambang akan dikonversi menjadi 1 (putih).
marcel_binary = np.zeros((panjang, lebar), dtype=np.uint8) # Perbaikan: menambahkan tipe data uint8 pada inisialisasi array

for i in range(panjang):
    for j in range(lebar):
        if marcel_gray[i,j] >= ambang:
            marcel_binary[i,j] = 0
        else :
            marcel_binary[i,j] = 1
            


In [16]:
marcel.imshow('pict asli', marcel_gray)
marcel.waitKey(0)
marcel.destroyAllWindows()

In [17]:
print(marcel_gray[50,50])

166


In [18]:
print(marcel_binary[50,50])

1
